# Generated by Django 4.1.4 on 2023-01-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_habilidad',
            field=models.ManyToManyField(to='empleados.habilidades'),
        ),
    ]
