# Generated by Django 4.1.4 on 2023-01-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombre Completo'),
        ),
    ]
