# Generated by Django 4.1.4 on 2023-01-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_empleado_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
